name: Go

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
        
    - name: Format
      run: |
        set -ex

        test -z $(gofmt -l .)
      
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
        
    - name: Vet
      run: go vet ./...

    - name: Static Check
      run: go run honnef.co/go/tools/cmd/staticcheck@latest

  build:
    strategy:
      matrix:
        version:
          - 'stable'
          # TODO: add 'oldstable' when 1.22 comes out
          
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.version }}

    - name: Build
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
        
    - name: Test
      run: go test -coverprofile=coverage.out -v ./...
      
    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out

